#g++ mainFloatArray1DAdvance.cpp floatArray1D.c

#CC=gcc
CC=g++
CFLAGS=-I.

mainMake: mainFloatArray1DAdvance.cpp floatArray1D.c
	$(CC) -o mainFloatArray1DAdvance mainFloatArray1DAdvance.cpp floatArray1D.c -I.